name: "Setup Python project"
description: "Setup Python, install Poetry, and install project dependencies"
inputs:
  python-version:
    description: "Python version to install"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Install system dependencies"
      shell: bash
      run: |
        sudo rm -f /etc/apt/sources.list.d/azure-cli.list /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt-get update
        sudo apt-get install -y libxml2-dev libxslt-dev
    - name: "Set up Python"
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ inputs.python-version }}
    - name: "Install Poetry"
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: "Install dependencies"
      shell: bash
      run: make dependencies
