# SonarCloud configuration
# Note: sonar.organization, sonar.projectKey, and sonar.python.coverage.reportPaths
# are set via GitHub Action parameters

sonar.host.url=https://sonarcloud.io
sonar.qualitygate.wait=true
sonar.sourceEncoding=UTF-8
# source file to be analyzed
sonar.sources=.github,pathology-api,mocks,infrastructure,scripts,Makefile
sonar.exclusions=docs/**,**/test-artefacts/**,**/coverage-html/**,pathology-api/src/**/test_*.py,**/__pycache__/**,**/.venv/**,mocks/src/**/test_*.py

# test files to be analyzed
sonar.tests=pathology-api,mocks
sonar.test.inclusions=pathology-api/**/test_*.py, pathology-api/tests/**,mocks/**/test_*.py, mocks/tests/**

sonar.coverage.exclusions=**/tests/**,**/features/**,**/test_*.py,infrastructure/images/api-gateway-mock/resources/**,**/infrastructure/environments/preview/**
# Set Python version for more precise analysis
sonar.python.version=3.14
