name: "Test stage"

env:
  BASE_URL: "http://localhost:5002"
  HOST: "localhost"
  ENV: "local"

on:
  workflow_call:
    inputs:
      python_version:
        description: "Python version, set by the CI/CD pipeline workflow"
        required: true
        type: string

jobs:
  create-coverage-name:
    name: "Create coverage artefact name"
    runs-on: ubuntu-latest
    outputs:
      coverage-name: ${{ steps.create_name.outputs.artefact-name }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - id: create_name
        name: "Generate unique coverage artefact name"
        uses: ./.github/actions/create-artefact-name
        with:
          prefix: coverage

  test-unit:
    name: "Unit tests"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "Setup Python project"
        uses: ./.github/actions/setup-python-project
        with:
          python-version: ${{ inputs.python_version }}
      - name: "Run unit test suite"
        run: make test-unit
      - name: "Upload unit test results for pathology-api"
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: unit-test-results
          path: pathology-api/test-artefacts/
          retention-days: 30
      - name: "Upload unit test results for mocks"
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: mock-unit-test-results
          path: mocks/test-artefacts/
          retention-days: 30
      - name: "Publish unit test results to summary"
        if: always()
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2.4
        with:
          paths: pathology-api/test-artefacts/unit-tests.xml
